PortalSscSig/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path
from usuario.views import home
from usuario.forms import LoginForm
from django.conf.urls.static import static
from django.conf import settings
from Hse.views import hse, novo_chamado_hse, home_empresa, show_cham_sol, show_my_cham, meus_chamados, include_col, message, gestao, message_sol, documentosHse, view_cham_hse, message_hse, saveCham, action, portaria, message_fun, doc_integracao,alter, resp, colaborador
from cadastro.views import cadastro_empresa, solicita, colaboradores, novo_fun, documentacao, cad_docs, exlude_fun, cad_resp_view, exlude_doc
from usuario.views import perfil, conf, usuarios, new_user, alt_perm, decide

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', home, name='home'),
    path(r'hse/', hse, name='hse'),
    path(r'login/', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm,}, name='login'),
    path(r'logout', views.logout, {'next_page': '/login'}), 
    path(r'novo_chamado_hse', novo_chamado_hse, name='novo_chamado_hse'),
    path(r'home_empresa', home_empresa, name='home_empresa'),
    path(r'cadastro_empresa', cadastro_empresa, name='cadastro_empresa'),
    path(r'perfil', perfil, name='perfil'),
    path(r'show_cham_sol/<str:nr>', show_cham_sol, name='show_cham_sol'),
    path(r'solicita', solicita, name='solicita'),
    path(r'<str:num_chamG>/<str:idG>/show_my_cham', show_my_cham, name='show_my_cham'), 
    path(r'colaboradores', colaboradores, name='colaboradores'),  
    path(r'novo_fun', novo_fun, name='novo_fun'),
    path(r'<str:idG>/<str:empG>/documentacao', documentacao, name='documentacao'), 
    path(r'cad_docs', cad_docs, name='cad_docs'),
    path(r'exlude_fun/<int:id>', exlude_fun, name='exlude_fun'),
    path(r'meus_chamados', meus_chamados, name='meus_chamados'),
    path(r'<int:num>/<int:id>/include_col', include_col, name='include_col'),
    path(r'<int:num>/<int:id>/message', message, name='message'),
    path(r'gestao', gestao, name='gestao'),
    path(r'message_sol/<int:num>/<slug:orig>', message_sol, name='message_sol'),
    path(r'<str:idG>/documentosHse', documentosHse, name='documentosHse'),
    path(r'<str:numG>/<str:idG>/view_cham_hse', view_cham_hse, name='view_cham_hse'),
    path(r'<int:num>/<int:id>/message_hse', message_hse, name='message_hse'),
    path(r'<int:num>/<int:id>/saveCham', saveCham, name='saveCham'),
    path(r'<int:id>/action', action, name='action'),
    path(r'<int:id>/message_fun', message_fun, name='message_fun'),
    path(r'portaria', portaria, name='portaria'),
    path(r'doc_integracao/<int:id>', doc_integracao, name='doc_integracao'),
    path(r'<int:num>/<int:id>/alter', alter, name='alter'),
    path(r'cad_resp_view', cad_resp_view, name='cad_resp_view'),
    path(r'resp/<str:idG>/<str:numG>', resp, name='resp'),
    path(r'colaborador/<str:id>', colaborador, name='colaborador'),
    path(r'conf', conf, name='conf'),
    path(r'usuarios', usuarios, name='usuarios'),
    path(r'new_user', new_user, name='new_user'),
    path(r'alt_perm/<int:id>', alt_perm, name='alt_perm'),
    path(r'decide', decide, name='decide'),
    path(r'exlude_doc/<str:idG>', exlude_doc, name='exlude_doc'),

    
    

]+ static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Hse/models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from django.contrib.auth.models import User
from cadastro.models import empresa_terc, cad_resp

default = 'default.png'

class chamado_hse(models.Model):
	solicitante = models.CharField(max_length=100)
	data_abertura = models.DateTimeField(auto_now_add=True)
	empresa = models.ForeignKey(empresa_terc, on_delete=models.CASCADE)
	tempo_estimado = models.CharField(max_length=100)
	nome_proj = models.CharField(max_length=100)
	setor_solicitante = models.CharField(max_length=100)
	gestor_solicitante = models.CharField(max_length=100)
	tipo_servico = models.CharField(max_length=50, blank=True)
	descricao = models.CharField(max_length=1000, blank=True)
	email_terc = models.CharField(max_length=500)
	email_solicitante = models.CharField(max_length=100)
	fone_solicitante = models.CharField(max_length=100)
	status = models.CharField(max_length=100)
	data = models.DateField(auto_now=True)
	resp_terc = models.CharField(max_length=100)

	def __str__(self):
		return '{}'.format(self.id)

class aux_table(models.Model):
	num_cham = models.IntegerField()
	tps = models.CharField(max_length=100)
	colab = models.CharField(max_length=100)
	id_col = models.CharField(max_length=55)
	status = models.CharField(max_length=10, default="AG")

	def __str__(self):
		return '{}'.format(self.id)

"""
class Solic_cad(models.Model):
	solicitante = models.CharField(max_length=100)
	nome_empresa = models.CharField(max_length=100)
	obs = models.CharField(max_length=500)
	first_access = models.IntegerField()

	def __str__(self):
		return '- {}'.format(self.Empresa)"""


class logs(models.Model):
	num_cham = models.CharField(max_length=100)
	ator = models.CharField(max_length=100)
	acao = models.CharField(max_length=10000)
	data = models.DateTimeField(default=datetime.now)
	tipo = models.CharField(max_length=100, default=None)

	def __str__(self):
		return '{}'.format(self.id)

class msg(models.Model):
	num_cham = models.CharField(max_length=100)
	ator = models.CharField(max_length=100)
	msg = models.CharField(max_length=10000)
	data = models.DateTimeField(default=datetime.now)
	tipo = models.CharField(max_length=10, default=None)
	id_col = models.CharField(max_length=10, default=None)

	def __str__(self):
		return '{}'.format(self.id)


class Hse(models.Model):
	Nome = models.CharField(max_length=10, default=None)

	def __str__(self):
		return '{}'.format(self.Nome)


class portaria(models.Model):
	Nome = models.CharField(max_length=10, default=None)

	def __str__(self):
		return '{}'.format(self.Nome)


cadastro/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime




default = 'default.png'

class Solic_cad(models.Model):
	Solicitante = models.CharField(max_length=100)
	Contato = models.CharField(max_length=100)
	Obs = models.CharField(max_length=1000)

	def __str__(self):
		return '- {}'.format(self.Empresa)

class empresa_terc(models.Model):
	nome_empresa = models.CharField(max_length=100)
	cnpj = models.CharField(max_length=20)
	telefone = models.CharField(max_length=50, blank=True)
	email = models.CharField(max_length=50, blank=True)
	usuario = models.CharField(max_length=50, blank=True)

	def __str__(self):
		return '- {}'.format(self.nome_empresa)

class cad_resp(models.Model):
	nome_resp = models.CharField(max_length=30)
	empresa_resp = models.CharField(max_length=30)
	funcao_resp = models.CharField(max_length=30)
	telefone_resp = models.CharField(max_length=30, blank=True)
	email_resp = models.CharField(max_length=500)

	def __str__(self):
		return '{}'.format(self.nome_resp)

class funcionario(models.Model):
	nome_funcionario = models.CharField(max_length=100)
	rg = models.CharField(max_length=20)
	cpf = models.CharField(max_length=20)
	empresa = models.ForeignKey(empresa_terc, on_delete=models.CASCADE)
	status = models.CharField(max_length=10, default="AG")
	funcao = models.CharField(max_length=100)
	data_int = models.DateField(null=True, blank=True)
	resp = models.ForeignKey(cad_resp, on_delete=models.CASCADE)

	def __str__(self):
		return '- {}'.format(self.nome_funcionario)
	

class documento(models.Model):
	nome_documento = models.CharField(max_length=100)
	validade_documento = models.CharField(max_length=30)
	arquivo_documento = models.FileField(upload_to='documents/')
	data_envio = models.DateTimeField(auto_now_add=True)
	funcionario = models.IntegerField()
	status = models.BooleanField(default=False)
	enviado = models.BooleanField(default=False)
	hse = models.CharField(max_length=2, default="AG")
	emp = models.CharField(max_length=100, default="none")

	def __str__(self):
		return '- {}'.format(self.nome_documento)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class docs_integracao(models.Model):
	validade_documento = models.DateField(auto_now=False)
	arquivo = models.FileField(upload_to='documents/')
	data_envio = models.DateTimeField(auto_now_add=True)
	funcionario = models.CharField(max_length=10)

	def __str__(self):
		return '- {}'.format(self.nome_documento)

class docs(models.Model):
	nome = models.CharField(max_length=30)
	txt1 = models.CharField(max_length=30)
	txt2 = models.CharField(max_length=30)
	tipo = models.CharField(max_length=30)
	toolTip = models.CharField(max_length=500)

	def __str__(self):
		return '{}'.format(self.nome)












usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from cadastro.models import empresa_terc
# Create your models here.

default = 'default.png'

class Perfil(models.Model):
	Permissoes = (
        ('SIG', 'SIG'),
        ('HSE', 'HSE'),
		('POR', 'PORTARIA'),
	)
	first_name = models.CharField(max_length=10, null=True)
	last_name = models.CharField(max_length=10, null=True)
	user = models.CharField(max_length=50 , null=True)
	user_id = models.CharField(max_length=30 , null=True)
	Setor = models.CharField(max_length=30 , null=True)
	Gestor = models.CharField(max_length=30 , null=True)
	email = models.CharField(max_length=80, null=True)
	funcao = models.CharField(max_length=30 , null=True)
	num_tel = models.CharField(max_length=30 , null=True)
	image = models.FileField(upload_to='documents/' , null=True)
	perm = models.CharField(max_length=3, choices=Permissoes , default="SIG", null=True)


	class Meta:
		verbose_name_plural = "Perfis"

	def __str__(self):
		return '->>>: {}'.format(self.user)

Hse/forms.py
from django import forms
from django.forms import ModelForm, ModelMultipleChoiceField
from Hse.models import chamado_hse, aux_table, msg
from cadastro.models import empresa_terc, cad_resp
from django.forms.widgets import Select
from django.db  import  models

TYPE_CHOICES = [
    ('1', "Trabalho em alta tensão e eletricidade"),
    ('2', "Trabalhos em altura "),
    ('3', "Espaços confinados "),
    ('4', "Operação de empilhadeira "),
    ('5', "Trabalhos com plataformas elevatórias"),
    ('6', "Operação de guindaste ou munk "),
    ('7', "Trabalhador autônomo - Firma individual "),
    ('8', " Assistência Técnica - mautenção "),
    ('9', " Soldador "),
]


class chamado_hseForm(ModelForm):
    tipo_servico = forms.MultipleChoiceField(choices=TYPE_CHOICES, 
    	                       widget=forms.CheckboxSelectMultiple(attrs={'class': 'flat', 'name': '','type': 'checkbox'}))
    empresa = forms.ModelChoiceField(queryset=empresa_terc.objects.all(), widget=Select(attrs={'class':'form-control', 'data-show-subtext':'true', 'data-live-search':'true'}))
    
    #resp_terc = forms.ModelChoiceField(queryset=cad_resp.objects.all(), widget=Select(attrs={'class':'form-control', 'data-show-subtext':'true', 'data-live-search':'true'}))
    

    nome_proj = forms.CharField(label="Nome Projeto / Serviço ", widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'vencimento','type': ''}))

    descricao = forms.CharField(label="Descricao", widget=forms.Textarea(attrs={'class': 'form-control', 'name': 'descricao','type': 'textarea'}))
    
    class Meta:
        model = chamado_hse
        fields = ['empresa','nome_proj','tipo_servico','descricao',]

class aux_tableForm(ModelForm):
    class Meta:
        model = aux_table
        fields = ['num_cham', 'tps','colab','id_col',]

class msgForm(ModelForm):
    class Meta:
        model = msg
        fields = ['num_cham', 'ator','msg',]

usuario/forms.py
from django.contrib.auth.forms import AuthenticationForm 
from django import forms
from usuario.models import Perfil
from django.forms import ModelForm

# If you don't do this you cannot use Bootstrap CSS
class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30, 
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30, 
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))

class PerfilForm(ModelForm):
    class Meta:
        model = Perfil
        fields = ['Setor', 'Gestor','funcao','num_tel','image','first_name','last_name', 'perm']

usuario/views.py
from django.shortcuts import render
from django.shortcuts import redirect 
from django.contrib.auth.decorators import login_required
from usuario.forms import PerfilForm
from usuario.models import Perfil
from django.contrib.auth.forms import UserCreationForm
from cadastro.models import empresa_terc
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import permission_required



#from Usuario.models import Perfil
# Create your views here.




@login_required(login_url="login/")
def home(request):
    emp = empresa_terc.objects.all()
    for el in emp:
        if el.usuario == request.user.username:
            return render(request, 'home_empresa.html',{'el':el})       
    if request.user.first_name == "first_access":
        return redirect('cadastro_empresa') 
    else:
        args = Perfil.objects.all()
        return render(request, 'index.html',{'args':args})

@login_required(login_url="login/")
def perfil(request):
    if request.method == 'POST':
        print("ok")
        form = PerfilForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            try:
                el = Perfil.objects.get(user = request.user.username)
            except:
                el = None
            if el:
                el.delete()
            post = form.save(commit=False)
            post.image = request.FILES.get('image')
            post.last_name = request.POST.get('last_name')
            post.user = request.POST.get('user')
            post.Setor = request.POST.get('Setor')
            post.Gestor = request.POST.get('Gestor')
            post.email = request.POST.get('email')
            post.perm = request.POST.get('perm')
            post.funcao = request.POST.get('funcao')
            post.num_tel = request.POST.get('num_tel')
            post.save()
            return redirect('perfil')
    try:
        el = Perfil.objects.get(user = request.user.username)
    except:
        el = None
    form = PerfilForm()
    return render(request, 'perfil.html', {'dado':el, 'form':form})  



@login_required(login_url="login/")
def conf(request):
    if request.user.has_perm('Hse.add_hse'):
        return render(request, 'conf.html')
    else:
        if request.user.first_name:
            return redirect('home_empresa')
        else:
            return redirect('hse')

@login_required(login_url="login/")
def usuarios(request):
    users = User.objects.all()
    perfil = Perfil.objects.all()
    form = PerfilForm()
    return render(request, 'usuarios.html', {'form':form, 'users': users, 'perfil':perfil})


def new_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('perfil')
    else:
        form = UserCreationForm()
    return render(request, 'new_user.html', {'form': form})


@login_required(login_url="login/")
def alt_perm(request, id):
    print(id)
    print(request.POST.get('perm'))
    print(request.POST.get('diff'))
    el = Perfil.objects.get(id=id)
    el.perm = request.POST.get('perm')
    el.save()
    u = User.objects.get(username=request.POST.get('diff'))
    if request.POST.get('perm') == "HSE":
        permissions =  Permission.objects.get(codename='add_hse')
    if request.POST.get('perm') == "POR":
        permissions =  Permission.objects.get(codename='add_portaria')
    if request.POST.get('perm') == "SIG":
        permissions =  Permission.objects.get(codename='add_perfil')
    print(permissions)
    u.user_permissions.add(permissions)
    return redirect('usuarios')


def decide(request):
    bias = request.user.first_name
    if bias:
        return redirect('cadastro_empresa')
    else:
        return redirect('perfil')

templates/Nsuccess.html
{% extends 'base.html' %}
{% block css %}{% endblock %}
{% block T1 %} {% endblock %}
{% block T2 %} {% endblock %}
{% block script %}
<script>
    function goBack() {
        window.history.back();
    }
    </script>
{% endblock %}
{% block content %}

<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">Óh não! Algo saiu errado! !</h4>
  <p>Ao gravar os dados informados ou ao enviar o e-mail de confirmação algo de inesperado aconteceu,</p>
  <hr>
  <p class="mb-0"><li>Verifique se a empresa que pretende associar a este email já não se encontra cadastrada.
                    <li>Verifique se você não informou caracteres não permitidos.</li><br><br>
  </li> <button onclick="goBack()">Retornar</button></p>
</div>
{% endblock %}

templates/cadastro_empresa.html
{% extends 'base.html' %}
{% load expr %}
{% load define_action %}
{% block css %}<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">{% endblock %}
{% block T1 %}Gestão Dados Cadastrais{% endblock %}
{% block T2 %}Cadastro, Responsáveis e Documentação{% endblock %}
{% block script %}
<script>
    $('#my_modal').on('show.bs.modal', function(e) {
      var bookId = $(e.relatedTarget).data('book-id');
      var txt = $(e.relatedTarget).data('txt-id');
      $(e.currentTarget).find('input[name="nome_documento"]').val(bookId);
      document.getElementById("demo").innerHTML = txt;
  });
  </script>
 
{% endblock %}


{% block content %}
<div class="row">
  <div class="col-md-6">
      <p class="lead text-muted">Dados Cadastrais da  Empresa</p>
      <form method="POST" class="post-form">{% csrf_token %}
          Razão :<br>
          <input class="form-control" type="txt" name="nome_empresa" value="{{nome}}"/><br>
          Cnpj:<br>
          <input class="form-control" type="txt" name="cnpj" value="{{cnpj}}"/><br>
          Telefone:<br>
          <input class="form-control" type="txt" name="telefone" value="{{telefone}}"/><br>
          Email:<br>
          <input class="form-control" type="txt" name="email" value="{{email}}"/>
          <br>
          <button type="submit" class="save btn btn-primary">Submeter Informações</button>
      </form>

  </div>


<dic class="col-md-6">
    <p class="lead text-muted">Cadastro de Novo Responsável</p>
    <form action="/cad_resp_view" method="POST" class="post-form">{% csrf_token %}
        None :<br>
        <input class="form-control" type="txt" name="nome_resp" value=""/><br>

        <input class="form-control" type="hidden" name="empresa_resp" value="{{empr_aux}}"/>
        Função:<br>
        <input class="form-control" type="txt" name="funcao_resp" value=""/><br>
        Telefone:<br>
        <input class="form-control" type="txt" name="telefone_resp" value=""/><br>
        Email:<br>
        <input class="form-control" type="txt" name="email_resp" value=""/>
        <br>
        <button type="submit" class="save btn btn-primary">Cadastrar Responsável</button>
    </form>
</div>
</div>
<div class="row">
    <div class="col-md-2"></div>

<div class="col-md-8" style="text-align: center">
    <p class="lead text-muted">Documentação Específica Empresa</p>
    <table class="table table-hover">
     <tr>
       <th>Documento Necessário</th>
       <th>Enviado (x) vezes</th>
     </tr>
     {% for k, v in dict1.items %}
     <tr>
       <td data-toggle="tooltip" data-placement="left" title="{{el.toolTip}}&#013;&#013;&#013;&#013;mais qqr coisa"
       ><a href="#my_modal" data-toggle="modal" data-book-id="{{k}}" data-txt-id="{{k}}">{{k}}</td></a>
       <td>
           {% if v  %}
               {% for item in v %}
                  <a href="/media/{{item}}"  target="_blank"  ><i class="fa fa-arrow-up" style="font-size:20px;color:green"></i></a>
               {% endfor %}
           {% else %}
              <i class="fa fa-arrow-down" style="font-size:20px;color:rgb(128, 0, 0)"></i>
           {% endif %}
       </td>   
   
     </tr>
     {% endfor %}
    </table>
   </div>
   <div class="col-md-2"></div>

  </div>
  <div class="row">
    <div class="col-md-2"></div>
      <div class="col-md-8" style="text-align: center">
          <p class="lead text-muted">Responsáveis Cadastrados</p>
          <table class="table table-hover">
           <tr>
             <th>Nome {{empr_id}}</th>
             <th>Função</th>
             <th>id</th>
             <th>E-mail</th>
           </tr>
           {% for elem in resp  %}

           {% if elem.empresa_resp|trim ==  empr_aux|trim %}
           
                    <tr>
                      <td>{{elem.nome_resp}}</td>
                      <td>{{elem.funcao_resp}}</td> 
                      <td>{{elem.empresa_resp}}</td> 
                      <td>{{elem.email_resp}}</td>     
                    </tr>

            {% endif %}

           {% endfor %}
          </table>
         </div>
         <div class="col-md-2"></div>
        </div>
        

   <div class="col-md-2" style="text-align: center"></div>
   <div class="modal" id="my_modal">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Envido Documento<p id="demo"></p></h4>
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              
          </div>
          <div class="modal-body">

              <div class="row">
                  <div class="col-md-2"></div>
                <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
                  <input type="hidden" name="nome_documento" value=""/>
                  <input type="hidden" name="enviado" value="1"/>
                  <label>Validade do Documento:</label><br>
                  <input class="form-control" type="text" name="validade_documento" id="outra_data" maxlength="10" onkeypress="mascaraData( this, event )" /><br><br>
                  <label>Selecione o arquivo:</label><br>
                  <input class="form-control" type="file" name="arquivo_documento" required="" id="id_arquivo_documento">
                 <br><br>
                  <button type="submit" class="btn btn-primary">Gravar Envio</button>
                </form>
                </div>
              </div>






          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>

    </div>
      

{% endblock %}

templates/colaborador.html
{% extends 'base.html' %}
{% block css %}{% endblock %}
{% block T1 %}Dados do Colaborador{% endblock %}
{% block T2 %}Visualize dados para conferência{% endblock %}
{% block script %}{% endblock %}
{% block content %}
<div class="row">
        <div class="col-md-12" style="text-align: right">
            <input class="btn btn-primary" type=button value="VOLTAR" onClick="javascript:history.go(-1);">
        </div>
    </div>
<main role="main">
        <div class="container">
            <h4 class="modal-title" id="myModalLabel">Nome : {{func.nome_funcionario|title}}</h4><br>
            <p class="lead text-muted"><strong>Empresa &nbsp: &nbsp </strong>
            &nbsp{% for nome in empw %}
                {% if nome.id == func.empresa_id %}
                {{nome.nome_empresa}}
                {% endif %}
                {% endfor %}
            </p>
          <p class="lead text-muted"><strong>Rg &nbsp: &nbsp </strong>&nbsp{{func.rg}}</p>
          <p class="lead text-muted"><strong>Cpf&nbsp&nbsp&nbsp&nbsp: &nbsp </strong>&nbsp{{func.cpf}}</p>
          <p class="lead text-muted"><strong>Função&nbsp&nbsp&nbsp&nbsp: &nbsp </strong>&nbsp{{func.funcao}}</p>
          <p class="lead text-muted"><strong>Data da Integração &nbsp: &nbsp </strong>&nbsp
            {% if func.data_int %}
            {{func.data_int}}
            {% else %}
            DATA NÃO DEFINIDA
            {% endif %}
        </p>

        </div>

        

       

{% endblock %}


templates/novo_fun.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css %}{% endblock %}
{% block T1 %}Novo Colaborador{% endblock %}
{% block T2 %}Gestão e Cadastro de Colaboradores{% endblock %}
{% block script %}{% endblock %}
{% block content %}

        
 

      


          <div class="row">
              <div class="col-md-6">
                <form method="POST" >{% csrf_token %}
 
            
                  <input type="hidden" name="status" value="False">
                  <p><label for="id_nome_funcionario">Nome funcionario:</label> <input class="form-control" type="text" name="nome_funcionario" maxlength="100" required="" id="id_nome_funcionario"></p>
                  <p><label for="id_rg">Rg:</label></p><input class="form-control" type="text" name="rg" maxlength="20" required="" id="id_rg"></p>
                  <p><label for="id_cpf">Cpf:</label> <input class="form-control" type="text" name="cpf" maxlength="20" required="" id="id_cpf"></p>
                  <p><label for="id_funcao">Funcao:</label> <input class="form-control" type="text" name="funcao" maxlength="100" required="" id="id_funcao"></p>
                  <p><label for="id_funcao">Responsável:</label>
                    
                    <select name="resp" class="form-control">
                        {% for el in resp %}
                        <option value="{{el.id}}">{{el.nome_resp}}</option>
                        {% endfor %}
                      </select></p>
                      <button type="submit" class="btn btn-primary">Cadastrar Colaborador</button>
                      </form>
                   </div>
                  
                   {% if form.errors %}
                   <div class="col-md-6" style="text-align: center" id="div1" >
                       
                       <img src="{% static 'SIG_1.png' %}" width="150" height="100" alt="Book" id="book" >
                       <p style="color:red;">Algo saiu errado ! Por favor, tente novamente.</p>
                       
                       <span class="helptext">Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.</span>
                       <span class="helptext"<ul><li>Sua senha não pode ser tão parecida com suas outras informações pessoais.</li><li>Sua senha precisa conter pelo menos 8 caracteres.</li><li>Sua senha não pode ser uma senha habitualmente utilizada.</li><li>Sua senha não pode ser inteiramente numérica.</li></ul></span>
                       <span class="helptext">Certifique-se de que as senhas informadas são identicas.</span><br>
                       <span class="helptext">Certifique-se de que não há outro usuário com o mesmo nome.</span>
                   
                       
                   </div>
                   {% else %}
                   <div class="col-md-6" style="text-align: center" id="div1" >
                       <br><br>
                       <img src="{% static 'SIG_1.png' %}" width="300 " height="200" alt="Book" id="book" >
                       
                   
                       
                   </div>
                   {% endif %}    
            
             
            
            </div>

{% endblock %}
